### ISSUE TITLE
NFR - Quantity Selector

### ISSUE THREAD

**Issue by benfavre** [Shreerang/Vue-Nuggets#1]
Add props : 
- Step interval (Step up/down by X)
- Steps Array (Allow stepper to traverse an array of possible values)

Great work, keep it up, looking good

**Comment by Shreerang** [comment]
Hi @benfavre. Thanks for your suggestions to adding these props. However, am not targeting just any counter. This is a counter specific for e-commerce sites. I don't see a use case for stepInterval and stepsArray. Do you have a use case in mind or an e-commerce site that allows you to do any of these things?

**Comment by Shreerang** [comment]
@benfavre it would be great if you can provide a e-commerce use case for this request, else am going to close this defect/ feature request!

**Comment by benfavre** [comment]
Hi.
I sell products for a print shop and we have preset quantities (eg: 100,200,300,400).
It does make sense to use a "select" element in some places, but on the cart page I use a stepper for consistency reasons.

My stepper has a Min value of 100  a max Value of 400 and a step interval of 100.

In some more complex scenarios I iterate over the array as you step up/down.
So yes this is an e-commerce use case

**Comment by Shreerang** [comment]
This is a really good use case @benfavre. I will work on it and add it to the Quantity Selector component 👨‍💻

**Comment by Shreerang** [comment]
Adding a reference link for this use case - https://www.onlinelabels.com/Products/OL713WX.htm?qty=100&src=mp-1&utm_source=GoogleProductSearch&utm_medium=ProductSearch&utm_term=OL713WX&utm_content=100Sheets&utm_campaign=ProductSearch&gclid=Cj0KCQiA3IPgBRCAARIsABb-iGJag8QIVbKilfjx8vLDeyR1-bT_vGh4l3M7aLqXPz4phu1vZFasBFgaAvamEALw_wcB

**Comment by Shreerang** [comment]
I was thinking of different ways to implement this and need your input on the following @benfavre.

**1. Step interval (Step up/down by X)**
Does the UI seem good for the implementation?

**2. Steps Array (Allow stepper to traverse an array of possible values)**
Would the variance selector component suffice this requirement? I think it's a pretty nice way of doing it! The quantity selector component as is, would not present strong UX for this use case. If variance selector is not used, select (drop-down) would be the only option left, which is not great!

I have pushed the code for both these cases to Github. Take a look at - http://ecommerce-vue-nuggets.herokuapp.com (Fourth case in the Quantity selector section and the last case in the Variance Selector Section)

**Comment by benfavre** [comment]
Nice !

1. I think i like all the UI/UX combinations implemented. I would maybe like to see an option to step up by x with only "+/-" and not "+/-2x"  (argument: you didn't implement "+/-1x")
2. I think i like all the UI/UX combinations implemented. I would like to see a helper wrapper-div ? or an alternative implementation of some css, to prevent the page from "jumping" when you initially select an element.

I agree with the various UX considerations. I think what I'm describing is "simply" a "non standard" implementation of a composite element that would be a combination of a stepper surrounding/linked with a select element.

**Comment by Shreerang** [comment]
@benfavre a few design decisions that drove my previous response.

**Reg point 1**
1. When **x is 1**; that is default and a most commonly implemented use case. In this cases users will expect the step to be incremented or decremented by 1 only. So no need to signify +/-1.
2. When **x is greater than 1** (x is configurable), which I am guessing will also be a lesser used use case, we need to inform the user that the step will now be incremented or decremented by **x**, which in this case is 2 (x=2). So the **+2 and -2 instead of just + and -**
3. If x is 10, we will show **+10 and -10** in the stepper, so that the user knows that the product can be bought only in multiples of 10.
4. If there are any CSS changes that you wish to make to a component, you can use the classes defined on each component. Also feel free to use your own classes for over-riding default component styles.

**Reg point 2**
1. The page "jump" is because of the difference between the border widths of the selected and the unselected box. The unselected box is 1px and the selected is 3px and hence the "jump".
2. A developer using this component can override the styles using the `nugget-` classes of by defining their own CSS classes. This is true in case of all the components am building.

Also, I strongly believe that we do not need a "non standard" implementation of a composite element that would be a combination of a stepper linked with a select element. The variance selector component will completely satisfy the requirement.

The only point of argument or disagreement would be the UI. If the custom arrayStepper has to look exactly like the stepper (quantity selector component), then I would encourage you to build one. Feel free to fork my repo.

Thanks a lot for your feedback and feature suggestions. Am closing this defect as fixed! 😄 👨‍💻

**Comment by benfavre** [comment]
Thanks, happy with all the responses, I agree fully.
Good luck with the lib. Looking Great.
++
